
package vn.meg.bossservice.vnp;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AppAcceptService", targetNamespace = "http://www.bnet.cn/v3.0/", wsdlLocation = "http://192.168.254.30:10000/services/AppAcceptService?wsdl")
public class AppAcceptService_Service
    extends Service
{

    private final static URL APPACCEPTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(vn.meg.bossservice.vnp.AppAcceptService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = vn.meg.bossservice.vnp.AppAcceptService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.254.30:10000/services/AppAcceptService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.254.30:10000/services/AppAcceptService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        APPACCEPTSERVICE_WSDL_LOCATION = url;
    }

    public AppAcceptService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppAcceptService_Service() {
        super(APPACCEPTSERVICE_WSDL_LOCATION, new QName("http://www.bnet.cn/v3.0/", "AppAcceptService"));
    }

    /**
     * 
     * @return
     *     returns AppAcceptService
     */
    @WebEndpoint(name = "AppAcceptService")
    public AppAcceptService getAppAcceptService() {
        return super.getPort(new QName("http://www.bnet.cn/v3.0/", "AppAcceptService"), AppAcceptService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppAcceptService
     */
    @WebEndpoint(name = "AppAcceptService")
    public AppAcceptService getAppAcceptService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bnet.cn/v3.0/", "AppAcceptService"), AppAcceptService.class, features);
    }

}
