
package vn.meg.bossservice.vnp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AppAcceptService", targetNamespace = "http://www.bnet.cn/v3.0/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AppAcceptService {


    /**
     * 
     * @param acceptReq
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.bnet.cn/v3.0/accept")
    @WebResult(name = "acceptResp", targetNamespace = "http://www.bnet.cn/v3.0/", partName = "acceptResp")
    public String accept(
        @WebParam(name = "acceptReq", targetNamespace = "http://www.bnet.cn/v3.0/", partName = "acceptReq")
        String acceptReq);

    /**
     * 
     * @param userSyncReq
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.bnet.cn/v3.0/userSync")
    @WebResult(name = "userSyncResp", targetNamespace = "http://www.bnet.cn/v3.0/", partName = "userSyncResp")
    public String userSync(
        @WebParam(name = "userSyncReq", targetNamespace = "http://www.bnet.cn/v3.0/", partName = "userSyncReq")
        String userSyncReq);

    /**
     * 
     * @param productUseAuthReq
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.bnet.cn/v3.0/productUseAuth")
    @WebResult(name = "productUseAuthResp", targetNamespace = "http://www.bnet.cn/v3.0/", partName = "productUseAuthResp")
    public String productUseAuth(
        @WebParam(name = "productUseAuthReq", targetNamespace = "http://www.bnet.cn/v3.0/", partName = "productUseAuthReq")
        String productUseAuthReq);

    /**
     * 
     * @param acceptCompleteNotifyReq
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.bnet.cn/v3.0/acceptCompleteNotify")
    @WebResult(name = "acceptCompleteNotifyResp", targetNamespace = "http://www.bnet.cn/v3.0/", partName = "acceptCompleteNotifyResp")
    public String acceptCompleteNotify(
        @WebParam(name = "acceptCompleteNotifyReq", targetNamespace = "http://www.bnet.cn/v3.0/", partName = "acceptCompleteNotifyReq")
        String acceptCompleteNotifyReq);

}
